### ISSUE TITLE
Problem in running Routing_ROS_Module

### ISSUE THREAD

**Issue by amar-crypto** [sylvainar/Routing-ROS-Module#1]
After cloning https://github.com/sylvainar/Routing-ROS-Module in a catkin workspace, I am not able to understand how  to run the code on ROS to get the route. Please help me in this situation.  Iam new to ROS.

**Comment by amar-crypto** [comment]
I am able to run the code. But,the code stops after showing "Routing Machine Ready". How to solve this.

**Comment by fbponz** [comment]
Hi jjkllll, showing "Routing Machine Ready" doesn't mean nothing more than you setup correctly a service. That service response when some call to "routing_machine/get_wpts"service. The principal reason you don't have all the source code it is because is this service is part of a bigger project, but that project is for company and is not shared throw github. But i can explain how you can use this node. You must create a action capable of connect with a ROS navigation system, this node shall be capable to manage services too with the same structure of a service than this package. But if you don't want do that, probably you can use this node https://github.com/RobotnikAutomation/robotnik_movebase_planner the functionallity it's the same that our module and probably you can adapt easily. Good Luck and Have fun coding.
